export const STARTERS = 'starters'
export const MAINS = 'mains'
export const DESSERTS = 'desserts'
export const LIMITED_DISH_ID = '11'
export const FISH_STARTER_ID = '4'
export const FISH_MAIN_ID = '7'